---
plugin: script
# Au lieu de donner juste le chemin, on force l'interpréteur
# Cela évite qu'Ansible vérifie si le fichier est exécutable ou non
path: /usr/bin/python3 inventory/mysql_inventory.py
