---
# On utilise le plugin officiel au lieu d'un script Python "maison"
plugin: community.general.mysql_query

# Informations de connexion à ta base MySQL (VM 1)
login_host: 172.16.23.161
login_user: awx_lecteur
login_password: PassAWX_789!
login_db: lab_inventory

# La requête SQL pour extraire tes données
# On récupère le nom de l'hôte, l'IP, le constructeur et le rôle
query: "SELECT hostname, ip_address, vendor, role FROM devices WHERE status = 'Production'"

# --- MAPPING : On transforme les données SQL en données Ansible ---

# Le nom de la machine dans Ansible sera la colonne 'hostname'
column_to_host: hostname

# On définit l'adresse IP de connexion (ansible_host)
compose:
  ansible_host: ip_address

# On crée des groupes automatiques basés sur les colonnes 'vendor' et 'role'
keyed_groups:
  - prefix: constructeur
    key: vendor
  - prefix: fonction
    key: role
