---
plugin: script
# On utilise le chemin absolu utilisé par AWX (/runner/project/)
# Et on force l'appel à python3 pour bypasser les problèmes de bit +x
path: python3 /runner/project/inventory/mysql_inventory.py
