---
- hosts: all
  become: yes

  tasks:

    - name: Installer nginx
      ansible.builtin.package:
        name: nginx
        state: present

    - name: Vérifier la configuration nginx
      ansible.builtin.command: nginx -t
      register: nginx_check
      ignore_errors: yes

    - name: Afficher le résultat du test nginx
      ansible.builtin.debug:
        var: nginx_check.stdout_lines

    - name: Redémarrer nginx si la config est valide
      ansible.builtin.service:
        name: nginx
        state: restarted
        enabled: yes
      when: nginx_check.rc == 0
