---
- hosts: all
  become: yes
  become_method: sudo
  become_user: root
  tasks:
    - name: Suppression brutale du paquet et des dépendances
      ansible.builtin.package:
        name: nginx
        state: absent
        purge: yes # Pour Debian/Ubuntu principalement

    - name: Supprimer les fichiers binaires restants (au cas où)
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /usr/sbin/nginx
        - /usr/local/nginx
        - /etc/nginx
        - /var/log/nginx

    - name: Vérifier si le binaire existe encore
      ansible.builtin.command: which nginx
      register: nginx_check
      ignore_errors: yes

    - name: Affichage du résultat
      ansible.builtin.debug:
        msg: "Nginx est toujours là : {{ nginx_check.stdout }}"
      when: nginx_check.rc == 0
