---
- hosts: all
  become: yes  # <--- C'EST CETTE LIGNE QUI MANQUE !
  tasks:
    - name: Arrêter le service Nginx
      ansible.builtin.service:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Désinstaller le paquet Nginx
      ansible.builtin.package:
        name: nginx
        state: absent
