---
- name: Aruba Connectivity Test
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: arubaoss
    ansible_command_timeout: 30
  tasks:
    - name: Debug connection variables
      ansible.builtin.debug:
        msg:
          ansible_connection: "{{ ansible_connection | default('undefined') }}"
          ansible_network_os: "{{ ansible_network_os | default('undefined') }}"
    - name: Show version
      ansible.netcommon.cli_command:
        command: show version
      register: show_version
    - name: Display result
      ansible.builtin.debug:
        var: show_version.stdout_lines
