---
- name: Aruba 2930F Connectivity Test
  hosts: all
  gather_facts: false
  connection: network_cli

  tasks:
    - name: Run show version
      ansible.netcommon.cli_command:
        command: show version
      register: show_version

    - name: Display show version
      ansible.builtin.debug:
        var: show_version.stdout_lines
